on: [push]

env:
  VERSION: 1.0.0-g${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          scope: ${{ github.repository_owner }}
          registry-url: https://npm.pkg.github.com

      - name: Create a package called @${{ github.repository }}
        run: npm init --scope ${{ github.repository_owner }} -y

      - name: Set package version to ${{ env.VERSION }}
        run: npm version ${{ env.VERSION }} --no-git-tag-version

      - name: Build the package
        run: npm pack

      - name: Publish the package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
